JO_COMPILE_WITH_VIDEO_MODULE = 0
JO_COMPILE_WITH_BACKUP_MODULE = 0
JO_COMPILE_WITH_TGA_MODULE = 1
JO_COMPILE_WITH_AUDIO_MODULE = 1
JO_COMPILE_WITH_3D_MODULE = 0
JO_COMPILE_WITH_PSEUDO_MODE7_MODULE = 0
JO_COMPILE_WITH_EFFECTS_MODULE = 0
JO_COMPILE_WITH_STORYBOARD_MODULE = 1
JO_GLOBAL_MEMORY_SIZE_FOR_MALLOC = 262144
JO_DEBUG = 1

# Video mode: NTSC hi-res interlaced, 704x480 (the Saturn's highest).
# JO_NTSC = 1 plus JO_480i = 1 selects TV_704x480 in jo/conf.h.
# (PAL plus JO_480i gives 704x256 instead, not 480 lines.)
JO_NTSC = 1
JO_480i = 1

SRCS=main.c
JO_ENGINE_SRC_DIR=../../jo_engine
COMPILER_DIR=../../Compiler
include $(COMPILER_DIR)/COMMON/jo_engine_makefile

# Project-specific Sega Saturn disc metadata.
IPFILE = ./IP.BIN
MKISOFS_FLAGS = -quiet -sysid "SEGA SATURN" -volid "BULLET_SYMPHONY_NO_1" -volset "BULLET_SYMPHONY_NO_1" -sectype 2352 \
	-publisher "WIZ ARTS DIGITAL" -preparer "WIZ ARTS DIGITAL" -appid "Bullet Symphony No.1" \
	-abstract "$(ASSETS_DIR)/ABS.TXT" -copyright "$(ASSETS_DIR)/CPY.TXT" -biblio "$(ASSETS_DIR)/BIB.TXT" -generic-boot $(IPFILE) \
	-full-iso9660-filenames -o $(TARGET2) $(ASSETS_DIR) $(ENTRYPOINT)
